name: flutter_silakehtm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get_cli: ^1.8.1
  intl: ^0.17.0
  get_storage: ^2.0.3
  curved_navigation_bar: ^1.0.3
  awesome_dialog: ^3.0.0
  flutter_vector_icons: ^1.0.0
  sizer: ^2.0.15
  get: ^4.6.5
  dropdown_search: ^5.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo.png
    - assets/detail_dok.png
    - assets/bottom1.png
    - assets/bottom2.png
    - assets/circle_account.jpg
    - assets/top1.png
    - assets/top2.png
    - assets/back.png
    - assets/permintaan_ranap.png
    - assets/pindah_bed.png
    - assets/permintaan_ok.png
    - assets/jadwal_ok.png
    - assets/keluar_ranap.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_bold.ttf
  uses-material-design: true

